linters-settings:
  lll:
    line-length: 120
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cloudnative-pg/cloudnative-pg)
      - blank
      - dot
  gosec:
    excludes:
      - G101 # remove this exclude when https://github.com/securego/gosec/issues/1001 is fixed

linters:
  enable-all: true
  disable:
    - execinquery
    - gomnd

issues:
  exclude-rules:
    # Allow dot imports for ginkgo and gomega
    - source: ginkgo|gomega
      linters:
      - revive
      text: "should not use dot imports"
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - goconst
    # Exclude lll issues for lines with long annotations
    - linters:
      - lll
      source: "//\\s*\\+"
    # We have no control of this in zz_generated files and it looks like that excluding those files is not enough
    # so we disable "ST1016: methods on the same type should have the same receiver name" in api directory
    - linters:
      - stylecheck
      text: "ST1016:"
      path: api/
  exclude-use-default: false
  exclude-files:
    - "zz_generated.*"
