version: '3'

tasks:
  protolint:
    desc: Run protolint
    cmds:
      - dagger call -m dagger/protolint lint --source . --args "--config_path=.protolint.yaml" --args proto/ stdout
    sources:
      - proto/**/*.proto

  protoc-gen-go-grpc:
    desc: Compile proto files
    deps:
      - protolint
    cmds:
      - >
        dagger call -m dagger/protoc-gen-go-grpc run --source . --go-opt module=github.com/cloudnative-pg/cnpg-i
        --go-grpcopt module=github.com/cloudnative-pg/cnpg-i --proto-path proto -o .
    sources:
      - proto/**/*.proto

  lint:
    desc: Run golangci-lint
    deps:
      - protoc-gen-go-grpc
    cmds:
      - >
        dagger call -m github.com/sagikazarmark/daggerverse/golangci-lint@157bf2192a7a1e8672da2c4fee37d8710734c35a
        run --source . --config .golangci.yml
    sources:
      - ./**/*.go

  protoc-gen-doc:
    desc: Generate documentation from proto files
    cmds:
      - dagger call -m dagger/protoc-gen-doc generate --proto-dir proto -o docs
    sources:
      - proto/**/*.proto

  build:
    desc: Build the project
    deps:
      - lint
      - protoc-gen-doc
    cmds:
      - >
        dagger --debug -m github.com/kpenfound/dagger-modules/golang@8d662e001caf8c16253226d0d456f2f0f374f009
        call base --version 1.22-bookworm  build --source . --args ./...

  commitlint:
    desc: Check for conventional commits
    cmds:
      - dagger call -m dagger/commitlint lint --source . --args "--from=main" stdout

  uncommitted:
    desc: Check for uncommitted changes
    deps:
      - build
    cmds:
      - dagger call -m dagger/uncommitted/ check-uncommitted --source . stdout
    sources:
      - ./**

  ci:
    desc: Run the CI pipeline
    deps:
      - build
      - commitlint
      - uncommitted
