// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.2
// source: proto/wal.proto

package wal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WALCapability_RPC_Type int32

const (
	WALCapability_RPC_TYPE_UNSPECIFIED WALCapability_RPC_Type = 0
	// TYPE_ARCHIVE_WAL indicates that the Plugin is able to
	// reply to the Archive RPC request
	WALCapability_RPC_TYPE_ARCHIVE_WAL WALCapability_RPC_Type = 1
	// TYPE_RESTORE_WAL indicates that the Plugin is able to
	// reply to the Restore RPC request
	WALCapability_RPC_TYPE_RESTORE_WAL WALCapability_RPC_Type = 2
	// TYPE_STATUS indicates that the Plugin is able to
	// reply to the Status RPC request
	WALCapability_RPC_TYPE_STATUS WALCapability_RPC_Type = 3
	// TYPE_SET_FIRST_REQUIRED indicates that the Plugin is able to
	// reply to the SetFirstRequired RPC request
	WALCapability_RPC_TYPE_SET_FIRST_REQUIRED WALCapability_RPC_Type = 4
)

// Enum value maps for WALCapability_RPC_Type.
var (
	WALCapability_RPC_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_ARCHIVE_WAL",
		2: "TYPE_RESTORE_WAL",
		3: "TYPE_STATUS",
		4: "TYPE_SET_FIRST_REQUIRED",
	}
	WALCapability_RPC_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":        0,
		"TYPE_ARCHIVE_WAL":        1,
		"TYPE_RESTORE_WAL":        2,
		"TYPE_STATUS":             3,
		"TYPE_SET_FIRST_REQUIRED": 4,
	}
)

func (x WALCapability_RPC_Type) Enum() *WALCapability_RPC_Type {
	p := new(WALCapability_RPC_Type)
	*p = x
	return p
}

func (x WALCapability_RPC_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WALCapability_RPC_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_wal_proto_enumTypes[0].Descriptor()
}

func (WALCapability_RPC_Type) Type() protoreflect.EnumType {
	return &file_proto_wal_proto_enumTypes[0]
}

func (x WALCapability_RPC_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WALCapability_RPC_Type.Descriptor instead.
func (WALCapability_RPC_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{10, 0, 0}
}

type WALArchiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is REQUIRED. Value of this field is the JSON
	// serialization of the Cluster corresponding to the Pod being applied
	ClusterDefinition []byte `protobuf:"bytes,1,opt,name=cluster_definition,json=clusterDefinition,proto3" json:"cluster_definition,omitempty"`
	// This field is REQUIRED. Value of this field is the full path
	// of the WAL file that should be archived
	SourceFileName string `protobuf:"bytes,2,opt,name=source_file_name,json=sourceFileName,proto3" json:"source_file_name,omitempty"`
	// This field is OPTIONAL. Values are opaque.
	Parameters map[string]string `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *WALArchiveRequest) Reset() {
	*x = WALArchiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WALArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALArchiveRequest) ProtoMessage() {}

func (x *WALArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALArchiveRequest.ProtoReflect.Descriptor instead.
func (*WALArchiveRequest) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{0}
}

func (x *WALArchiveRequest) GetClusterDefinition() []byte {
	if x != nil {
		return x.ClusterDefinition
	}
	return nil
}

func (x *WALArchiveRequest) GetSourceFileName() string {
	if x != nil {
		return x.SourceFileName
	}
	return ""
}

func (x *WALArchiveRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type WALArchiveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WALArchiveResult) Reset() {
	*x = WALArchiveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WALArchiveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALArchiveResult) ProtoMessage() {}

func (x *WALArchiveResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALArchiveResult.ProtoReflect.Descriptor instead.
func (*WALArchiveResult) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{1}
}

type WALRestoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is REQUIRED. Value of this field is the JSON
	// serialization of the Cluster corresponding to the Pod being applied
	ClusterDefinition []byte `protobuf:"bytes,1,opt,name=cluster_definition,json=clusterDefinition,proto3" json:"cluster_definition,omitempty"`
	// This field is REQUIRED. Value of this field is the name of
	// the WAL to be retrieved from the archive, such as:
	// 000000010000000100000012
	SourceWalName string `protobuf:"bytes,2,opt,name=source_wal_name,json=sourceWalName,proto3" json:"source_wal_name,omitempty"`
	// This field is REQUIRED. Value of this field is the full path
	// where the WAL file should be stored
	DestinationFileName string `protobuf:"bytes,3,opt,name=destination_file_name,json=destinationFileName,proto3" json:"destination_file_name,omitempty"`
	// This field is OPTIONAL. Values are opaque.
	Parameters map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *WALRestoreRequest) Reset() {
	*x = WALRestoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WALRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALRestoreRequest) ProtoMessage() {}

func (x *WALRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALRestoreRequest.ProtoReflect.Descriptor instead.
func (*WALRestoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{2}
}

func (x *WALRestoreRequest) GetClusterDefinition() []byte {
	if x != nil {
		return x.ClusterDefinition
	}
	return nil
}

func (x *WALRestoreRequest) GetSourceWalName() string {
	if x != nil {
		return x.SourceWalName
	}
	return ""
}

func (x *WALRestoreRequest) GetDestinationFileName() string {
	if x != nil {
		return x.DestinationFileName
	}
	return ""
}

func (x *WALRestoreRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type WALRestoreResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WALRestoreResult) Reset() {
	*x = WALRestoreResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WALRestoreResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALRestoreResult) ProtoMessage() {}

func (x *WALRestoreResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALRestoreResult.ProtoReflect.Descriptor instead.
func (*WALRestoreResult) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{3}
}

type WALStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is REQUIRED. Value of this field is the JSON
	// serialization of the Cluster corresponding to the Pod being applied
	ClusterDefinition []byte `protobuf:"bytes,1,opt,name=cluster_definition,json=clusterDefinition,proto3" json:"cluster_definition,omitempty"`
}

func (x *WALStatusRequest) Reset() {
	*x = WALStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WALStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALStatusRequest) ProtoMessage() {}

func (x *WALStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALStatusRequest.ProtoReflect.Descriptor instead.
func (*WALStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{4}
}

func (x *WALStatusRequest) GetClusterDefinition() []byte {
	if x != nil {
		return x.ClusterDefinition
	}
	return nil
}

type WALStatusResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is REQUIRED. Value of this field is the base name of
	// the oldest archived WAL, such as:
	// 000000010000000100000012
	FirstWal string `protobuf:"bytes,1,opt,name=first_wal,json=firstWal,proto3" json:"first_wal,omitempty"`
	// This field is REQUIRED. Value of this field is the base name of
	// the newest archived WAL, such as:
	// 000000010000000100000014
	LastWal string `protobuf:"bytes,2,opt,name=last_wal,json=lastWal,proto3" json:"last_wal,omitempty"`
	// This field is OPTIONAL. Value is opaque.
	AdditionalInformation map[string]string `protobuf:"bytes,4,rep,name=additional_information,json=additionalInformation,proto3" json:"additional_information,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *WALStatusResult) Reset() {
	*x = WALStatusResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WALStatusResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALStatusResult) ProtoMessage() {}

func (x *WALStatusResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALStatusResult.ProtoReflect.Descriptor instead.
func (*WALStatusResult) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{5}
}

func (x *WALStatusResult) GetFirstWal() string {
	if x != nil {
		return x.FirstWal
	}
	return ""
}

func (x *WALStatusResult) GetLastWal() string {
	if x != nil {
		return x.LastWal
	}
	return ""
}

func (x *WALStatusResult) GetAdditionalInformation() map[string]string {
	if x != nil {
		return x.AdditionalInformation
	}
	return nil
}

type SetFirstRequiredRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is REQUIRED. Value of this field is the JSON
	// serialization of the Cluster corresponding to the Pod being applied
	ClusterDefinition []byte `protobuf:"bytes,1,opt,name=cluster_definition,json=clusterDefinition,proto3" json:"cluster_definition,omitempty"`
	// This field is REQUIRED. Value of this field is the name of the first
	// required WAL in the WAL archive for this cluster (normally based on the
	// begin WAL of the first available base backup for the cluster)
	FirstRequiredWal string `protobuf:"bytes,2,opt,name=first_required_wal,json=firstRequiredWal,proto3" json:"first_required_wal,omitempty"`
}

func (x *SetFirstRequiredRequest) Reset() {
	*x = SetFirstRequiredRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFirstRequiredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFirstRequiredRequest) ProtoMessage() {}

func (x *SetFirstRequiredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFirstRequiredRequest.ProtoReflect.Descriptor instead.
func (*SetFirstRequiredRequest) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{6}
}

func (x *SetFirstRequiredRequest) GetClusterDefinition() []byte {
	if x != nil {
		return x.ClusterDefinition
	}
	return nil
}

func (x *SetFirstRequiredRequest) GetFirstRequiredWal() string {
	if x != nil {
		return x.FirstRequiredWal
	}
	return ""
}

type SetFirstRequiredResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetFirstRequiredResult) Reset() {
	*x = SetFirstRequiredResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFirstRequiredResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFirstRequiredResult) ProtoMessage() {}

func (x *SetFirstRequiredResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFirstRequiredResult.ProtoReflect.Descriptor instead.
func (*SetFirstRequiredResult) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{7}
}

type WALCapabilitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WALCapabilitiesRequest) Reset() {
	*x = WALCapabilitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WALCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALCapabilitiesRequest) ProtoMessage() {}

func (x *WALCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*WALCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{8}
}

type WALCapabilitiesResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// All the capabilities that the controller service supports. This
	// field is OPTIONAL.
	Capabilities []*WALCapability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
}

func (x *WALCapabilitiesResult) Reset() {
	*x = WALCapabilitiesResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WALCapabilitiesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALCapabilitiesResult) ProtoMessage() {}

func (x *WALCapabilitiesResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALCapabilitiesResult.ProtoReflect.Descriptor instead.
func (*WALCapabilitiesResult) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{9}
}

func (x *WALCapabilitiesResult) GetCapabilities() []*WALCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type WALCapability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*WALCapability_Rpc
	Type isWALCapability_Type `protobuf_oneof:"type"`
}

func (x *WALCapability) Reset() {
	*x = WALCapability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wal_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WALCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALCapability) ProtoMessage() {}

func (x *WALCapability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALCapability.ProtoReflect.Descriptor instead.
func (*WALCapability) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{10}
}

func (m *WALCapability) GetType() isWALCapability_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *WALCapability) GetRpc() *WALCapability_RPC {
	if x, ok := x.GetType().(*WALCapability_Rpc); ok {
		return x.Rpc
	}
	return nil
}

type isWALCapability_Type interface {
	isWALCapability_Type()
}

type WALCapability_Rpc struct {
	Rpc *WALCapability_RPC `protobuf:"bytes,1,opt,name=rpc,proto3,oneof"`
}

func (*WALCapability_Rpc) isWALCapability_Type() {}

type WALCapability_RPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type WALCapability_RPC_Type `protobuf:"varint,1,opt,name=type,proto3,enum=cnpgi.wal.v1.WALCapability_RPC_Type" json:"type,omitempty"`
}

func (x *WALCapability_RPC) Reset() {
	*x = WALCapability_RPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wal_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WALCapability_RPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALCapability_RPC) ProtoMessage() {}

func (x *WALCapability_RPC) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALCapability_RPC.ProtoReflect.Descriptor instead.
func (*WALCapability_RPC) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{10, 0}
}

func (x *WALCapability_RPC) GetType() WALCapability_RPC_Type {
	if x != nil {
		return x.Type
	}
	return WALCapability_RPC_TYPE_UNSPECIFIED
}

var File_proto_wal_proto protoreflect.FileDescriptor

var file_proto_wal_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x22,
	0xfc, 0x01, 0x0a, 0x11, 0x57, 0x41, 0x4c, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x11, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x4f,
	0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x57, 0x41, 0x4c, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a,
	0x3d, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x12,
	0x0a, 0x10, 0x57, 0x41, 0x4c, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0xae, 0x02, 0x0a, 0x11, 0x57, 0x41, 0x4c, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x77, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x57, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x32, 0x0a, 0x15, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x4f, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e,
	0x77, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x41, 0x4c, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x12, 0x0a, 0x10, 0x57, 0x41, 0x4c, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x41, 0x0a, 0x10, 0x57, 0x41, 0x4c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x84, 0x02, 0x0a, 0x0f, 0x57,
	0x41, 0x4c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x77, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x72, 0x73, 0x74, 0x57, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x77, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x61, 0x73, 0x74, 0x57, 0x61, 0x6c, 0x12, 0x6f, 0x0a, 0x16, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77,
	0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x41, 0x4c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x15, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x48, 0x0a, 0x1a, 0x41, 0x64, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x76, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x46, 0x69, 0x72, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x12,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x77, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x69, 0x72, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x57, 0x61, 0x6c, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x65, 0x74,
	0x46, 0x69, 0x72, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x57, 0x41, 0x4c, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x58, 0x0a,
	0x15, 0x57, 0x41, 0x4c, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3f, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63,
	0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x41, 0x4c, 0x43,
	0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x86, 0x02, 0x0a, 0x0d, 0x57, 0x41, 0x4c, 0x43,
	0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x33, 0x0a, 0x03, 0x72, 0x70, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77,
	0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x41, 0x4c, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x2e, 0x52, 0x50, 0x43, 0x48, 0x00, 0x52, 0x03, 0x72, 0x70, 0x63, 0x1a, 0xb7,
	0x01, 0x0a, 0x03, 0x52, 0x50, 0x43, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x41, 0x4c, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x76, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14,
	0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x52, 0x43, 0x48, 0x49, 0x56, 0x45, 0x5f, 0x57,
	0x41, 0x4c, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x53,
	0x54, 0x4f, 0x52, 0x45, 0x5f, 0x57, 0x41, 0x4c, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x46, 0x49, 0x52, 0x53, 0x54, 0x5f, 0x52, 0x45,
	0x51, 0x55, 0x49, 0x52, 0x45, 0x44, 0x10, 0x04, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x32, 0xaf, 0x03, 0x0a, 0x03, 0x57, 0x41, 0x4c, 0x12, 0x5e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x24, 0x2e, 0x63, 0x6e,
	0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x41, 0x4c, 0x43, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x57, 0x41, 0x4c, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x07, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x12, 0x1f, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x57, 0x41, 0x4c, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x41, 0x4c, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x12, 0x1f, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x57, 0x41, 0x4c, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x57, 0x41, 0x4c, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e,
	0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x41,
	0x4c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x41,
	0x4c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12,
	0x61, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x46, 0x69, 0x72, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x12, 0x25, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x46, 0x69, 0x72, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6e, 0x70,
	0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x46, 0x69, 0x72,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x2d, 0x70, 0x67, 0x2f,
	0x63, 0x6e, 0x70, 0x67, 0x2d, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x77, 0x61, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_wal_proto_rawDescOnce sync.Once
	file_proto_wal_proto_rawDescData = file_proto_wal_proto_rawDesc
)

func file_proto_wal_proto_rawDescGZIP() []byte {
	file_proto_wal_proto_rawDescOnce.Do(func() {
		file_proto_wal_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_wal_proto_rawDescData)
	})
	return file_proto_wal_proto_rawDescData
}

var file_proto_wal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_wal_proto_goTypes = []interface{}{
	(WALCapability_RPC_Type)(0),     // 0: cnpgi.wal.v1.WALCapability.RPC.Type
	(*WALArchiveRequest)(nil),       // 1: cnpgi.wal.v1.WALArchiveRequest
	(*WALArchiveResult)(nil),        // 2: cnpgi.wal.v1.WALArchiveResult
	(*WALRestoreRequest)(nil),       // 3: cnpgi.wal.v1.WALRestoreRequest
	(*WALRestoreResult)(nil),        // 4: cnpgi.wal.v1.WALRestoreResult
	(*WALStatusRequest)(nil),        // 5: cnpgi.wal.v1.WALStatusRequest
	(*WALStatusResult)(nil),         // 6: cnpgi.wal.v1.WALStatusResult
	(*SetFirstRequiredRequest)(nil), // 7: cnpgi.wal.v1.SetFirstRequiredRequest
	(*SetFirstRequiredResult)(nil),  // 8: cnpgi.wal.v1.SetFirstRequiredResult
	(*WALCapabilitiesRequest)(nil),  // 9: cnpgi.wal.v1.WALCapabilitiesRequest
	(*WALCapabilitiesResult)(nil),   // 10: cnpgi.wal.v1.WALCapabilitiesResult
	(*WALCapability)(nil),           // 11: cnpgi.wal.v1.WALCapability
	nil,                             // 12: cnpgi.wal.v1.WALArchiveRequest.ParametersEntry
	nil,                             // 13: cnpgi.wal.v1.WALRestoreRequest.ParametersEntry
	nil,                             // 14: cnpgi.wal.v1.WALStatusResult.AdditionalInformationEntry
	(*WALCapability_RPC)(nil),       // 15: cnpgi.wal.v1.WALCapability.RPC
}
var file_proto_wal_proto_depIdxs = []int32{
	12, // 0: cnpgi.wal.v1.WALArchiveRequest.parameters:type_name -> cnpgi.wal.v1.WALArchiveRequest.ParametersEntry
	13, // 1: cnpgi.wal.v1.WALRestoreRequest.parameters:type_name -> cnpgi.wal.v1.WALRestoreRequest.ParametersEntry
	14, // 2: cnpgi.wal.v1.WALStatusResult.additional_information:type_name -> cnpgi.wal.v1.WALStatusResult.AdditionalInformationEntry
	11, // 3: cnpgi.wal.v1.WALCapabilitiesResult.capabilities:type_name -> cnpgi.wal.v1.WALCapability
	15, // 4: cnpgi.wal.v1.WALCapability.rpc:type_name -> cnpgi.wal.v1.WALCapability.RPC
	0,  // 5: cnpgi.wal.v1.WALCapability.RPC.type:type_name -> cnpgi.wal.v1.WALCapability.RPC.Type
	9,  // 6: cnpgi.wal.v1.WAL.GetCapabilities:input_type -> cnpgi.wal.v1.WALCapabilitiesRequest
	1,  // 7: cnpgi.wal.v1.WAL.Archive:input_type -> cnpgi.wal.v1.WALArchiveRequest
	3,  // 8: cnpgi.wal.v1.WAL.Restore:input_type -> cnpgi.wal.v1.WALRestoreRequest
	5,  // 9: cnpgi.wal.v1.WAL.Status:input_type -> cnpgi.wal.v1.WALStatusRequest
	7,  // 10: cnpgi.wal.v1.WAL.SetFirstRequired:input_type -> cnpgi.wal.v1.SetFirstRequiredRequest
	10, // 11: cnpgi.wal.v1.WAL.GetCapabilities:output_type -> cnpgi.wal.v1.WALCapabilitiesResult
	2,  // 12: cnpgi.wal.v1.WAL.Archive:output_type -> cnpgi.wal.v1.WALArchiveResult
	4,  // 13: cnpgi.wal.v1.WAL.Restore:output_type -> cnpgi.wal.v1.WALRestoreResult
	6,  // 14: cnpgi.wal.v1.WAL.Status:output_type -> cnpgi.wal.v1.WALStatusResult
	8,  // 15: cnpgi.wal.v1.WAL.SetFirstRequired:output_type -> cnpgi.wal.v1.SetFirstRequiredResult
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_wal_proto_init() }
func file_proto_wal_proto_init() {
	if File_proto_wal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_wal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WALArchiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WALArchiveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WALRestoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WALRestoreResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WALStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WALStatusResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFirstRequiredRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wal_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFirstRequiredResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wal_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WALCapabilitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wal_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WALCapabilitiesResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wal_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WALCapability); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wal_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WALCapability_RPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_wal_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*WALCapability_Rpc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_wal_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wal_proto_goTypes,
		DependencyIndexes: file_proto_wal_proto_depIdxs,
		EnumInfos:         file_proto_wal_proto_enumTypes,
		MessageInfos:      file_proto_wal_proto_msgTypes,
	}.Build()
	File_proto_wal_proto = out.File
	file_proto_wal_proto_rawDesc = nil
	file_proto_wal_proto_goTypes = nil
	file_proto_wal_proto_depIdxs = nil
}
