// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/reconciler.proto

package reconciler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReconcilerHooksCapability_Kind int32

const (
	ReconcilerHooksCapability_KIND_UNSPECIFIED ReconcilerHooksCapability_Kind = 0
	// KIND_CLUSTER indicates that the plugin will plug the
	// Cluster reconciler
	ReconcilerHooksCapability_KIND_CLUSTER ReconcilerHooksCapability_Kind = 1
	// KIND_BACKUP indicates that the plugin will plug the
	// Backup reconciler
	ReconcilerHooksCapability_KIND_BACKUP ReconcilerHooksCapability_Kind = 2
)

// Enum value maps for ReconcilerHooksCapability_Kind.
var (
	ReconcilerHooksCapability_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_CLUSTER",
		2: "KIND_BACKUP",
	}
	ReconcilerHooksCapability_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_CLUSTER":     1,
		"KIND_BACKUP":      2,
	}
)

func (x ReconcilerHooksCapability_Kind) Enum() *ReconcilerHooksCapability_Kind {
	p := new(ReconcilerHooksCapability_Kind)
	*p = x
	return p
}

func (x ReconcilerHooksCapability_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReconcilerHooksCapability_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_reconciler_proto_enumTypes[0].Descriptor()
}

func (ReconcilerHooksCapability_Kind) Type() protoreflect.EnumType {
	return &file_proto_reconciler_proto_enumTypes[0]
}

func (x ReconcilerHooksCapability_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReconcilerHooksCapability_Kind.Descriptor instead.
func (ReconcilerHooksCapability_Kind) EnumDescriptor() ([]byte, []int) {
	return file_proto_reconciler_proto_rawDescGZIP(), []int{2, 0}
}

type ReconcilerHooksResult_Behavior int32

const (
	ReconcilerHooksResult_BEHAVIOR_UNSPECIFIED ReconcilerHooksResult_Behavior = 0
	// BEHAVIOR_CONTINUE indicates that this reconciliation loop will
	// proceed running.
	// BEHAVIOR_CONTINUE is useful when the plugin executes changes on internal status or resources not directly managed
	// by the main reconciliation loop
	ReconcilerHooksResult_BEHAVIOR_CONTINUE ReconcilerHooksResult_Behavior = 1
	// BEHAVIOR_REQUEUE indicates that this reconciliation loop will
	// be stopped and a new one will be requested.
	// BEHAVIOR_REQUEUE should always be set when the plugin applies changes on resources that are directly managed
	// by the main reconciliation loop
	ReconcilerHooksResult_BEHAVIOR_REQUEUE ReconcilerHooksResult_Behavior = 2
	// BEHAVIOR_TERMINATE indicates that the main reconciliation loop needs to
	// be marked as succeeded and no further operations needs to be taken.
	// This should be used when the invoked Reconcile hook act as a substitute for the main CNPG reconciliation loop.
	// An example would be a plugin that substitutes the `Backup` logic of CNPG.
	ReconcilerHooksResult_BEHAVIOR_TERMINATE ReconcilerHooksResult_Behavior = 3
)

// Enum value maps for ReconcilerHooksResult_Behavior.
var (
	ReconcilerHooksResult_Behavior_name = map[int32]string{
		0: "BEHAVIOR_UNSPECIFIED",
		1: "BEHAVIOR_CONTINUE",
		2: "BEHAVIOR_REQUEUE",
		3: "BEHAVIOR_TERMINATE",
	}
	ReconcilerHooksResult_Behavior_value = map[string]int32{
		"BEHAVIOR_UNSPECIFIED": 0,
		"BEHAVIOR_CONTINUE":    1,
		"BEHAVIOR_REQUEUE":     2,
		"BEHAVIOR_TERMINATE":   3,
	}
)

func (x ReconcilerHooksResult_Behavior) Enum() *ReconcilerHooksResult_Behavior {
	p := new(ReconcilerHooksResult_Behavior)
	*p = x
	return p
}

func (x ReconcilerHooksResult_Behavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReconcilerHooksResult_Behavior) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_reconciler_proto_enumTypes[1].Descriptor()
}

func (ReconcilerHooksResult_Behavior) Type() protoreflect.EnumType {
	return &file_proto_reconciler_proto_enumTypes[1]
}

func (x ReconcilerHooksResult_Behavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReconcilerHooksResult_Behavior.Descriptor instead.
func (ReconcilerHooksResult_Behavior) EnumDescriptor() ([]byte, []int) {
	return file_proto_reconciler_proto_rawDescGZIP(), []int{4, 0}
}

type ReconcilerHooksCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcilerHooksCapabilitiesRequest) Reset() {
	*x = ReconcilerHooksCapabilitiesRequest{}
	mi := &file_proto_reconciler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcilerHooksCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcilerHooksCapabilitiesRequest) ProtoMessage() {}

func (x *ReconcilerHooksCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcilerHooksCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*ReconcilerHooksCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_reconciler_proto_rawDescGZIP(), []int{0}
}

type ReconcilerHooksCapabilitiesResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This message is OPTIONAL, containing the list of resources
	// for which the lifecycle hook is called
	ReconcilerCapabilities []*ReconcilerHooksCapability `protobuf:"bytes,1,rep,name=reconciler_capabilities,json=reconcilerCapabilities,proto3" json:"reconciler_capabilities,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReconcilerHooksCapabilitiesResult) Reset() {
	*x = ReconcilerHooksCapabilitiesResult{}
	mi := &file_proto_reconciler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcilerHooksCapabilitiesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcilerHooksCapabilitiesResult) ProtoMessage() {}

func (x *ReconcilerHooksCapabilitiesResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcilerHooksCapabilitiesResult.ProtoReflect.Descriptor instead.
func (*ReconcilerHooksCapabilitiesResult) Descriptor() ([]byte, []int) {
	return file_proto_reconciler_proto_rawDescGZIP(), []int{1}
}

func (x *ReconcilerHooksCapabilitiesResult) GetReconcilerCapabilities() []*ReconcilerHooksCapability {
	if x != nil {
		return x.ReconcilerCapabilities
	}
	return nil
}

type ReconcilerHooksCapability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is the controller Kind
	Kind          ReconcilerHooksCapability_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=cnpgi.reconciler.v1.ReconcilerHooksCapability_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcilerHooksCapability) Reset() {
	*x = ReconcilerHooksCapability{}
	mi := &file_proto_reconciler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcilerHooksCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcilerHooksCapability) ProtoMessage() {}

func (x *ReconcilerHooksCapability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcilerHooksCapability.ProtoReflect.Descriptor instead.
func (*ReconcilerHooksCapability) Descriptor() ([]byte, []int) {
	return file_proto_reconciler_proto_rawDescGZIP(), []int{2}
}

func (x *ReconcilerHooksCapability) GetKind() ReconcilerHooksCapability_Kind {
	if x != nil {
		return x.Kind
	}
	return ReconcilerHooksCapability_KIND_UNSPECIFIED
}

type ReconcilerHooksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED. Value of this field is the JSON
	// serialization of the Cluster tied to the `Kind` being reconciled
	ClusterDefinition []byte `protobuf:"bytes,1,opt,name=cluster_definition,json=clusterDefinition,proto3" json:"cluster_definition,omitempty"`
	// This field is REQUIRED. Value of this field is the JSON
	// serialization of the resource being reconciled. Please note that in case of Cluster Reconciliation, the
	// `resource_definition` will match the `cluster_definition`
	ResourceDefinition []byte `protobuf:"bytes,2,opt,name=resource_definition,json=resourceDefinition,proto3" json:"resource_definition,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReconcilerHooksRequest) Reset() {
	*x = ReconcilerHooksRequest{}
	mi := &file_proto_reconciler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcilerHooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcilerHooksRequest) ProtoMessage() {}

func (x *ReconcilerHooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcilerHooksRequest.ProtoReflect.Descriptor instead.
func (*ReconcilerHooksRequest) Descriptor() ([]byte, []int) {
	return file_proto_reconciler_proto_rawDescGZIP(), []int{3}
}

func (x *ReconcilerHooksRequest) GetClusterDefinition() []byte {
	if x != nil {
		return x.ClusterDefinition
	}
	return nil
}

func (x *ReconcilerHooksRequest) GetResourceDefinition() []byte {
	if x != nil {
		return x.ResourceDefinition
	}
	return nil
}

// ReconcilerHooksResult response is used to instruct then the CNPG controller on which action
// take after the plugin execution.
type ReconcilerHooksResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED, and indicates the behavior that should
	// be used for the current reconciliation loop.
	Behavior ReconcilerHooksResult_Behavior `protobuf:"varint,1,opt,name=behavior,proto3,enum=cnpgi.reconciler.v1.ReconcilerHooksResult_Behavior" json:"behavior,omitempty"`
	// This field is OPTIONAL. If true, the current reconciliation loop
	// will be stopped and the operator will ensure that another one will
	// be run in the requested number of seconds. IMPORTANT: the new
	// reconciliation loop may start even before the number of specified
	// seconds.
	RequeueAfter  int64 `protobuf:"varint,2,opt,name=requeue_after,json=requeueAfter,proto3" json:"requeue_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcilerHooksResult) Reset() {
	*x = ReconcilerHooksResult{}
	mi := &file_proto_reconciler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcilerHooksResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcilerHooksResult) ProtoMessage() {}

func (x *ReconcilerHooksResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcilerHooksResult.ProtoReflect.Descriptor instead.
func (*ReconcilerHooksResult) Descriptor() ([]byte, []int) {
	return file_proto_reconciler_proto_rawDescGZIP(), []int{4}
}

func (x *ReconcilerHooksResult) GetBehavior() ReconcilerHooksResult_Behavior {
	if x != nil {
		return x.Behavior
	}
	return ReconcilerHooksResult_BEHAVIOR_UNSPECIFIED
}

func (x *ReconcilerHooksResult) GetRequeueAfter() int64 {
	if x != nil {
		return x.RequeueAfter
	}
	return 0
}

var File_proto_reconciler_proto protoreflect.FileDescriptor

const file_proto_reconciler_proto_rawDesc = "" +
	"\n" +
	"\x16proto/reconciler.proto\x12\x13cnpgi.reconciler.v1\"$\n" +
	"\"ReconcilerHooksCapabilitiesRequest\"\x8c\x01\n" +
	"!ReconcilerHooksCapabilitiesResult\x12g\n" +
	"\x17reconciler_capabilities\x18\x01 \x03(\v2..cnpgi.reconciler.v1.ReconcilerHooksCapabilityR\x16reconcilerCapabilities\"\xa5\x01\n" +
	"\x19ReconcilerHooksCapability\x12G\n" +
	"\x04kind\x18\x01 \x01(\x0e23.cnpgi.reconciler.v1.ReconcilerHooksCapability.KindR\x04kind\"?\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fKIND_CLUSTER\x10\x01\x12\x0f\n" +
	"\vKIND_BACKUP\x10\x02\"x\n" +
	"\x16ReconcilerHooksRequest\x12-\n" +
	"\x12cluster_definition\x18\x01 \x01(\fR\x11clusterDefinition\x12/\n" +
	"\x13resource_definition\x18\x02 \x01(\fR\x12resourceDefinition\"\xf8\x01\n" +
	"\x15ReconcilerHooksResult\x12O\n" +
	"\bbehavior\x18\x01 \x01(\x0e23.cnpgi.reconciler.v1.ReconcilerHooksResult.BehaviorR\bbehavior\x12#\n" +
	"\rrequeue_after\x18\x02 \x01(\x03R\frequeueAfter\"i\n" +
	"\bBehavior\x12\x18\n" +
	"\x14BEHAVIOR_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11BEHAVIOR_CONTINUE\x10\x01\x12\x14\n" +
	"\x10BEHAVIOR_REQUEUE\x10\x02\x12\x16\n" +
	"\x12BEHAVIOR_TERMINATE\x10\x032\xdd\x02\n" +
	"\x0fReconcilerHooks\x12\x84\x01\n" +
	"\x0fGetCapabilities\x127.cnpgi.reconciler.v1.ReconcilerHooksCapabilitiesRequest\x1a6.cnpgi.reconciler.v1.ReconcilerHooksCapabilitiesResult\"\x00\x12`\n" +
	"\x03Pre\x12+.cnpgi.reconciler.v1.ReconcilerHooksRequest\x1a*.cnpgi.reconciler.v1.ReconcilerHooksResult\"\x00\x12a\n" +
	"\x04Post\x12+.cnpgi.reconciler.v1.ReconcilerHooksRequest\x1a*.cnpgi.reconciler.v1.ReconcilerHooksResult\"\x00B1Z/github.com/cloudnative-pg/cnpg-i/pkg/reconcilerb\x06proto3"

var (
	file_proto_reconciler_proto_rawDescOnce sync.Once
	file_proto_reconciler_proto_rawDescData []byte
)

func file_proto_reconciler_proto_rawDescGZIP() []byte {
	file_proto_reconciler_proto_rawDescOnce.Do(func() {
		file_proto_reconciler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reconciler_proto_rawDesc), len(file_proto_reconciler_proto_rawDesc)))
	})
	return file_proto_reconciler_proto_rawDescData
}

var file_proto_reconciler_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_reconciler_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_reconciler_proto_goTypes = []any{
	(ReconcilerHooksCapability_Kind)(0),        // 0: cnpgi.reconciler.v1.ReconcilerHooksCapability.Kind
	(ReconcilerHooksResult_Behavior)(0),        // 1: cnpgi.reconciler.v1.ReconcilerHooksResult.Behavior
	(*ReconcilerHooksCapabilitiesRequest)(nil), // 2: cnpgi.reconciler.v1.ReconcilerHooksCapabilitiesRequest
	(*ReconcilerHooksCapabilitiesResult)(nil),  // 3: cnpgi.reconciler.v1.ReconcilerHooksCapabilitiesResult
	(*ReconcilerHooksCapability)(nil),          // 4: cnpgi.reconciler.v1.ReconcilerHooksCapability
	(*ReconcilerHooksRequest)(nil),             // 5: cnpgi.reconciler.v1.ReconcilerHooksRequest
	(*ReconcilerHooksResult)(nil),              // 6: cnpgi.reconciler.v1.ReconcilerHooksResult
}
var file_proto_reconciler_proto_depIdxs = []int32{
	4, // 0: cnpgi.reconciler.v1.ReconcilerHooksCapabilitiesResult.reconciler_capabilities:type_name -> cnpgi.reconciler.v1.ReconcilerHooksCapability
	0, // 1: cnpgi.reconciler.v1.ReconcilerHooksCapability.kind:type_name -> cnpgi.reconciler.v1.ReconcilerHooksCapability.Kind
	1, // 2: cnpgi.reconciler.v1.ReconcilerHooksResult.behavior:type_name -> cnpgi.reconciler.v1.ReconcilerHooksResult.Behavior
	2, // 3: cnpgi.reconciler.v1.ReconcilerHooks.GetCapabilities:input_type -> cnpgi.reconciler.v1.ReconcilerHooksCapabilitiesRequest
	5, // 4: cnpgi.reconciler.v1.ReconcilerHooks.Pre:input_type -> cnpgi.reconciler.v1.ReconcilerHooksRequest
	5, // 5: cnpgi.reconciler.v1.ReconcilerHooks.Post:input_type -> cnpgi.reconciler.v1.ReconcilerHooksRequest
	3, // 6: cnpgi.reconciler.v1.ReconcilerHooks.GetCapabilities:output_type -> cnpgi.reconciler.v1.ReconcilerHooksCapabilitiesResult
	6, // 7: cnpgi.reconciler.v1.ReconcilerHooks.Pre:output_type -> cnpgi.reconciler.v1.ReconcilerHooksResult
	6, // 8: cnpgi.reconciler.v1.ReconcilerHooks.Post:output_type -> cnpgi.reconciler.v1.ReconcilerHooksResult
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_reconciler_proto_init() }
func file_proto_reconciler_proto_init() {
	if File_proto_reconciler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reconciler_proto_rawDesc), len(file_proto_reconciler_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reconciler_proto_goTypes,
		DependencyIndexes: file_proto_reconciler_proto_depIdxs,
		EnumInfos:         file_proto_reconciler_proto_enumTypes,
		MessageInfos:      file_proto_reconciler_proto_msgTypes,
	}.Build()
	File_proto_reconciler_proto = out.File
	file_proto_reconciler_proto_goTypes = nil
	file_proto_reconciler_proto_depIdxs = nil
}
