// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.28.3
// source: proto/restore_job.proto

package job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestoreJobHooksCapability_Kind int32

const (
	RestoreJobHooksCapability_KIND_UNSPECIFIED RestoreJobHooksCapability_Kind = 0
	// KIND_RESTORE means that the plugin is able to handle
	// Restore requests
	RestoreJobHooksCapability_KIND_RESTORE RestoreJobHooksCapability_Kind = 1
)

// Enum value maps for RestoreJobHooksCapability_Kind.
var (
	RestoreJobHooksCapability_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_RESTORE",
	}
	RestoreJobHooksCapability_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_RESTORE":     1,
	}
)

func (x RestoreJobHooksCapability_Kind) Enum() *RestoreJobHooksCapability_Kind {
	p := new(RestoreJobHooksCapability_Kind)
	*p = x
	return p
}

func (x RestoreJobHooksCapability_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestoreJobHooksCapability_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_restore_job_proto_enumTypes[0].Descriptor()
}

func (RestoreJobHooksCapability_Kind) Type() protoreflect.EnumType {
	return &file_proto_restore_job_proto_enumTypes[0]
}

func (x RestoreJobHooksCapability_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestoreJobHooksCapability_Kind.Descriptor instead.
func (RestoreJobHooksCapability_Kind) EnumDescriptor() ([]byte, []int) {
	return file_proto_restore_job_proto_rawDescGZIP(), []int{2, 0}
}

type RestoreJobHooksCapabilitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RestoreJobHooksCapabilitiesRequest) Reset() {
	*x = RestoreJobHooksCapabilitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_restore_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreJobHooksCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreJobHooksCapabilitiesRequest) ProtoMessage() {}

func (x *RestoreJobHooksCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restore_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreJobHooksCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*RestoreJobHooksCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_restore_job_proto_rawDescGZIP(), []int{0}
}

type RestoreJobHooksCapabilitiesResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is REQUIRED and contains the describe capability
	Capabilities []*RestoreJobHooksCapability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
}

func (x *RestoreJobHooksCapabilitiesResult) Reset() {
	*x = RestoreJobHooksCapabilitiesResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_restore_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreJobHooksCapabilitiesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreJobHooksCapabilitiesResult) ProtoMessage() {}

func (x *RestoreJobHooksCapabilitiesResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restore_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreJobHooksCapabilitiesResult.ProtoReflect.Descriptor instead.
func (*RestoreJobHooksCapabilitiesResult) Descriptor() ([]byte, []int) {
	return file_proto_restore_job_proto_rawDescGZIP(), []int{1}
}

func (x *RestoreJobHooksCapabilitiesResult) GetCapabilities() []*RestoreJobHooksCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RestoreJobHooksCapability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind RestoreJobHooksCapability_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=cnpgi.wal.v1.RestoreJobHooksCapability_Kind" json:"kind,omitempty"`
}

func (x *RestoreJobHooksCapability) Reset() {
	*x = RestoreJobHooksCapability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_restore_job_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreJobHooksCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreJobHooksCapability) ProtoMessage() {}

func (x *RestoreJobHooksCapability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restore_job_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreJobHooksCapability.ProtoReflect.Descriptor instead.
func (*RestoreJobHooksCapability) Descriptor() ([]byte, []int) {
	return file_proto_restore_job_proto_rawDescGZIP(), []int{2}
}

func (x *RestoreJobHooksCapability) GetKind() RestoreJobHooksCapability_Kind {
	if x != nil {
		return x.Kind
	}
	return RestoreJobHooksCapability_KIND_UNSPECIFIED
}

type RestoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is REQUIRED. Value of this field is the JSON
	// serialization of the Cluster.
	ClusterDefinition []byte `protobuf:"bytes,1,opt,name=cluster_definition,json=clusterDefinition,proto3" json:"cluster_definition,omitempty"`
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_restore_job_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restore_job_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_restore_job_proto_rawDescGZIP(), []int{3}
}

func (x *RestoreRequest) GetClusterDefinition() []byte {
	if x != nil {
		return x.ClusterDefinition
	}
	return nil
}

type RestoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is REQUIRED. Value of this field is the string
	// representation of PostgreSQL configuration parameters to use
	// for the restore.
	RestoreConfig string `protobuf:"bytes,1,opt,name=restore_config,json=restoreConfig,proto3" json:"restore_config,omitempty"`
	// This field if REQUIRED. Environment variables to be set in the
	// restore job, expressed as NAME=VALUE.
	Envs []string `protobuf:"bytes,2,rep,name=envs,proto3" json:"envs,omitempty"`
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_restore_job_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restore_job_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_restore_job_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreResponse) GetRestoreConfig() string {
	if x != nil {
		return x.RestoreConfig
	}
	return ""
}

func (x *RestoreResponse) GetEnvs() []string {
	if x != nil {
		return x.Envs
	}
	return nil
}

var File_proto_restore_job_proto protoreflect.FileDescriptor

var file_proto_restore_job_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f,
	0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6e, 0x70, 0x67, 0x69,
	0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x24, 0x0a, 0x22, 0x52, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x4a, 0x6f, 0x62, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x70, 0x0a,
	0x21, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x48, 0x6f, 0x6f, 0x6b, 0x73,
	0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x4b, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69,
	0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4a,
	0x6f, 0x62, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22,
	0x8d, 0x01, 0x0a, 0x19, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x48, 0x6f,
	0x6f, 0x6b, 0x73, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x40, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x63, 0x6e,
	0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x4a, 0x6f, 0x62, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22,
	0x2e, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x10, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a,
	0x0c, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x53, 0x54, 0x4f, 0x52, 0x45, 0x10, 0x01, 0x22,
	0x3f, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x4c, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x6e,
	0x76, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x65, 0x6e, 0x76, 0x73, 0x32, 0xd3,
	0x01, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x48, 0x6f, 0x6f,
	0x6b, 0x73, 0x12, 0x76, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x30, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x48,
	0x6f, 0x6f, 0x6b, 0x73, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e,
	0x77, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4a, 0x6f,
	0x62, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x07, 0x52, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x77, 0x61, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x2d, 0x70,
	0x67, 0x2f, 0x63, 0x6e, 0x70, 0x67, 0x2d, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2f, 0x6a, 0x6f, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_restore_job_proto_rawDescOnce sync.Once
	file_proto_restore_job_proto_rawDescData = file_proto_restore_job_proto_rawDesc
)

func file_proto_restore_job_proto_rawDescGZIP() []byte {
	file_proto_restore_job_proto_rawDescOnce.Do(func() {
		file_proto_restore_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_restore_job_proto_rawDescData)
	})
	return file_proto_restore_job_proto_rawDescData
}

var file_proto_restore_job_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_restore_job_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_restore_job_proto_goTypes = []interface{}{
	(RestoreJobHooksCapability_Kind)(0),        // 0: cnpgi.wal.v1.RestoreJobHooksCapability.Kind
	(*RestoreJobHooksCapabilitiesRequest)(nil), // 1: cnpgi.wal.v1.RestoreJobHooksCapabilitiesRequest
	(*RestoreJobHooksCapabilitiesResult)(nil),  // 2: cnpgi.wal.v1.RestoreJobHooksCapabilitiesResult
	(*RestoreJobHooksCapability)(nil),          // 3: cnpgi.wal.v1.RestoreJobHooksCapability
	(*RestoreRequest)(nil),                     // 4: cnpgi.wal.v1.RestoreRequest
	(*RestoreResponse)(nil),                    // 5: cnpgi.wal.v1.RestoreResponse
}
var file_proto_restore_job_proto_depIdxs = []int32{
	3, // 0: cnpgi.wal.v1.RestoreJobHooksCapabilitiesResult.capabilities:type_name -> cnpgi.wal.v1.RestoreJobHooksCapability
	0, // 1: cnpgi.wal.v1.RestoreJobHooksCapability.kind:type_name -> cnpgi.wal.v1.RestoreJobHooksCapability.Kind
	1, // 2: cnpgi.wal.v1.RestoreJobHooks.GetCapabilities:input_type -> cnpgi.wal.v1.RestoreJobHooksCapabilitiesRequest
	4, // 3: cnpgi.wal.v1.RestoreJobHooks.Restore:input_type -> cnpgi.wal.v1.RestoreRequest
	2, // 4: cnpgi.wal.v1.RestoreJobHooks.GetCapabilities:output_type -> cnpgi.wal.v1.RestoreJobHooksCapabilitiesResult
	5, // 5: cnpgi.wal.v1.RestoreJobHooks.Restore:output_type -> cnpgi.wal.v1.RestoreResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_restore_job_proto_init() }
func file_proto_restore_job_proto_init() {
	if File_proto_restore_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_restore_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreJobHooksCapabilitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_restore_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreJobHooksCapabilitiesResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_restore_job_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreJobHooksCapability); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_restore_job_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_restore_job_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_restore_job_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_restore_job_proto_goTypes,
		DependencyIndexes: file_proto_restore_job_proto_depIdxs,
		EnumInfos:         file_proto_restore_job_proto_enumTypes,
		MessageInfos:      file_proto_restore_job_proto_msgTypes,
	}.Build()
	File_proto_restore_job_proto = out.File
	file_proto_restore_job_proto_rawDesc = nil
	file_proto_restore_job_proto_goTypes = nil
	file_proto_restore_job_proto_depIdxs = nil
}
