// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: proto/lifecycle.proto

package lifecycle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType_Type int32

const (
	OperationType_TYPE_PATCH  OperationType_Type = 0
	OperationType_TYPE_UPDATE OperationType_Type = 1
	OperationType_TYPE_CREATE OperationType_Type = 2
	OperationType_TYPE_DELETE OperationType_Type = 3
)

// Enum value maps for OperationType_Type.
var (
	OperationType_Type_name = map[int32]string{
		0: "TYPE_PATCH",
		1: "TYPE_UPDATE",
		2: "TYPE_CREATE",
		3: "TYPE_DELETE",
	}
	OperationType_Type_value = map[string]int32{
		"TYPE_PATCH":  0,
		"TYPE_UPDATE": 1,
		"TYPE_CREATE": 2,
		"TYPE_DELETE": 3,
	}
)

func (x OperationType_Type) Enum() *OperationType_Type {
	p := new(OperationType_Type)
	*p = x
	return p
}

func (x OperationType_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lifecycle_proto_enumTypes[0].Descriptor()
}

func (OperationType_Type) Type() protoreflect.EnumType {
	return &file_proto_lifecycle_proto_enumTypes[0]
}

func (x OperationType_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType_Type.Descriptor instead.
func (OperationType_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_lifecycle_proto_rawDescGZIP(), []int{3, 0}
}

type LifecycleCapabilities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group         string           `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Kind          string           `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	OperationType []*OperationType `protobuf:"bytes,3,rep,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
}

func (x *LifecycleCapabilities) Reset() {
	*x = LifecycleCapabilities{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lifecycle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleCapabilities) ProtoMessage() {}

func (x *LifecycleCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lifecycle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleCapabilities.ProtoReflect.Descriptor instead.
func (*LifecycleCapabilities) Descriptor() ([]byte, []int) {
	return file_proto_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *LifecycleCapabilities) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *LifecycleCapabilities) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LifecycleCapabilities) GetOperationType() []*OperationType {
	if x != nil {
		return x.OperationType
	}
	return nil
}

type LifecycleCapabilitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LifecycleCapabilities []*LifecycleCapabilities `protobuf:"bytes,1,rep,name=lifecycle_capabilities,json=lifecycleCapabilities,proto3" json:"lifecycle_capabilities,omitempty"`
}

func (x *LifecycleCapabilitiesResponse) Reset() {
	*x = LifecycleCapabilitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lifecycle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleCapabilitiesResponse) ProtoMessage() {}

func (x *LifecycleCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lifecycle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*LifecycleCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *LifecycleCapabilitiesResponse) GetLifecycleCapabilities() []*LifecycleCapabilities {
	if x != nil {
		return x.LifecycleCapabilities
	}
	return nil
}

type LifecycleCapabilitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LifecycleCapabilitiesRequest) Reset() {
	*x = LifecycleCapabilitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lifecycle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleCapabilitiesRequest) ProtoMessage() {}

func (x *LifecycleCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lifecycle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*LifecycleCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_lifecycle_proto_rawDescGZIP(), []int{2}
}

type OperationType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type OperationType_Type `protobuf:"varint,1,opt,name=type,proto3,enum=cnpgi.identity.v1.OperationType_Type" json:"type,omitempty"`
}

func (x *OperationType) Reset() {
	*x = OperationType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lifecycle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationType) ProtoMessage() {}

func (x *OperationType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lifecycle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationType.ProtoReflect.Descriptor instead.
func (*OperationType) Descriptor() ([]byte, []int) {
	return file_proto_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *OperationType) GetType() OperationType_Type {
	if x != nil {
		return x.Type
	}
	return OperationType_TYPE_PATCH
}

type LifecycleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is REQUIRED.
	OperationType *OperationType `protobuf:"bytes,1,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	// This field is REQUIRED
	ClusterDefinition []byte `protobuf:"bytes,2,opt,name=cluster_definition,json=clusterDefinition,proto3" json:"cluster_definition,omitempty"`
	// This field is REQUIRED.
	ObjectDefinition []byte `protobuf:"bytes,3,opt,name=object_definition,json=objectDefinition,proto3" json:"object_definition,omitempty"`
}

func (x *LifecycleRequest) Reset() {
	*x = LifecycleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lifecycle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleRequest) ProtoMessage() {}

func (x *LifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lifecycle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleRequest.ProtoReflect.Descriptor instead.
func (*LifecycleRequest) Descriptor() ([]byte, []int) {
	return file_proto_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *LifecycleRequest) GetOperationType() *OperationType {
	if x != nil {
		return x.OperationType
	}
	return nil
}

func (x *LifecycleRequest) GetClusterDefinition() []byte {
	if x != nil {
		return x.ClusterDefinition
	}
	return nil
}

func (x *LifecycleRequest) GetObjectDefinition() []byte {
	if x != nil {
		return x.ObjectDefinition
	}
	return nil
}

type LifecycleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is OPTIONAL.
	JsonPatch []byte `protobuf:"bytes,1,opt,name=json_patch,json=jsonPatch,proto3" json:"json_patch,omitempty"`
}

func (x *LifecycleResponse) Reset() {
	*x = LifecycleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lifecycle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleResponse) ProtoMessage() {}

func (x *LifecycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lifecycle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleResponse.ProtoReflect.Descriptor instead.
func (*LifecycleResponse) Descriptor() ([]byte, []int) {
	return file_proto_lifecycle_proto_rawDescGZIP(), []int{5}
}

func (x *LifecycleResponse) GetJsonPatch() []byte {
	if x != nil {
		return x.JsonPatch
	}
	return nil
}

var File_proto_lifecycle_proto protoreflect.FileDescriptor

var file_proto_lifecycle_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x8a, 0x01, 0x0a, 0x15, 0x4c,
	0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x47,
	0x0a, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x1d, 0x4c, 0x69, 0x66, 0x65,
	0x63, 0x79, 0x63, 0x6c, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x16, 0x6c, 0x69, 0x66,
	0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6e, 0x70, 0x67,
	0x69, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x52, 0x15, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x43, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x1e, 0x0a, 0x1c, 0x4c, 0x69,
	0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x95, 0x01, 0x0a, 0x0d, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x63, 0x6e, 0x70,
	0x67, 0x69, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x49, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x41, 0x54, 0x43, 0x48, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01,
	0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10,
	0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45,
	0x10, 0x03, 0x22, 0xb7, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x2d, 0x0a, 0x12, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2b, 0x0a, 0x11, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x32, 0x0a, 0x11,
	0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x74, 0x63, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6a, 0x73, 0x6f, 0x6e, 0x50, 0x61, 0x74, 0x63, 0x68,
	0x32, 0xe1, 0x01, 0x0a, 0x09, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x76,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x12, 0x2f, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x43,
	0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x30, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65,
	0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x0d, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79,
	0x63, 0x6c, 0x65, 0x48, 0x6f, 0x6f, 0x6b, 0x12, 0x23, 0x2e, 0x63, 0x6e, 0x70, 0x67, 0x69, 0x2e,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x66, 0x65,
	0x63, 0x79, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63,
	0x6e, 0x70, 0x67, 0x69, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x2d, 0x70,
	0x67, 0x2f, 0x63, 0x6e, 0x70, 0x67, 0x2d, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6c, 0x69, 0x66,
	0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_lifecycle_proto_rawDescOnce sync.Once
	file_proto_lifecycle_proto_rawDescData = file_proto_lifecycle_proto_rawDesc
)

func file_proto_lifecycle_proto_rawDescGZIP() []byte {
	file_proto_lifecycle_proto_rawDescOnce.Do(func() {
		file_proto_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lifecycle_proto_rawDescData)
	})
	return file_proto_lifecycle_proto_rawDescData
}

var file_proto_lifecycle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_lifecycle_proto_goTypes = []interface{}{
	(OperationType_Type)(0),               // 0: cnpgi.identity.v1.OperationType.Type
	(*LifecycleCapabilities)(nil),         // 1: cnpgi.identity.v1.LifecycleCapabilities
	(*LifecycleCapabilitiesResponse)(nil), // 2: cnpgi.identity.v1.LifecycleCapabilitiesResponse
	(*LifecycleCapabilitiesRequest)(nil),  // 3: cnpgi.identity.v1.LifecycleCapabilitiesRequest
	(*OperationType)(nil),                 // 4: cnpgi.identity.v1.OperationType
	(*LifecycleRequest)(nil),              // 5: cnpgi.identity.v1.LifecycleRequest
	(*LifecycleResponse)(nil),             // 6: cnpgi.identity.v1.LifecycleResponse
}
var file_proto_lifecycle_proto_depIdxs = []int32{
	4, // 0: cnpgi.identity.v1.LifecycleCapabilities.operation_type:type_name -> cnpgi.identity.v1.OperationType
	1, // 1: cnpgi.identity.v1.LifecycleCapabilitiesResponse.lifecycle_capabilities:type_name -> cnpgi.identity.v1.LifecycleCapabilities
	0, // 2: cnpgi.identity.v1.OperationType.type:type_name -> cnpgi.identity.v1.OperationType.Type
	4, // 3: cnpgi.identity.v1.LifecycleRequest.operation_type:type_name -> cnpgi.identity.v1.OperationType
	3, // 4: cnpgi.identity.v1.Lifecycle.GetCapabilities:input_type -> cnpgi.identity.v1.LifecycleCapabilitiesRequest
	5, // 5: cnpgi.identity.v1.Lifecycle.LifecycleHook:input_type -> cnpgi.identity.v1.LifecycleRequest
	2, // 6: cnpgi.identity.v1.Lifecycle.GetCapabilities:output_type -> cnpgi.identity.v1.LifecycleCapabilitiesResponse
	6, // 7: cnpgi.identity.v1.Lifecycle.LifecycleHook:output_type -> cnpgi.identity.v1.LifecycleResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_lifecycle_proto_init() }
func file_proto_lifecycle_proto_init() {
	if File_proto_lifecycle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lifecycle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleCapabilities); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lifecycle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleCapabilitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lifecycle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleCapabilitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lifecycle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lifecycle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lifecycle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lifecycle_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lifecycle_proto_goTypes,
		DependencyIndexes: file_proto_lifecycle_proto_depIdxs,
		EnumInfos:         file_proto_lifecycle_proto_enumTypes,
		MessageInfos:      file_proto_lifecycle_proto_msgTypes,
	}.Build()
	File_proto_lifecycle_proto = out.File
	file_proto_lifecycle_proto_rawDesc = nil
	file_proto_lifecycle_proto_goTypes = nil
	file_proto_lifecycle_proto_depIdxs = nil
}
