// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/operator_lifecycle.proto

package lifecycle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperatorOperationType_Type int32

const (
	OperatorOperationType_TYPE_UNSPECIFIED OperatorOperationType_Type = 0
	// This is invoked when the operator executes a Patch request on the resource
	OperatorOperationType_TYPE_PATCH OperatorOperationType_Type = 1
	// This is invoked when the operator executes an Update request on the resource
	OperatorOperationType_TYPE_UPDATE OperatorOperationType_Type = 2
	// This is invoked when the operator executes a Create request on the resource
	OperatorOperationType_TYPE_CREATE OperatorOperationType_Type = 3
	// This is invoked when the operator executes a Delete request on the resource
	OperatorOperationType_TYPE_DELETE OperatorOperationType_Type = 4
	// Reserved for future use.
	OperatorOperationType_TYPE_DEREGISTER OperatorOperationType_Type = 5
	// The operator calls this to perform a dry-run evaluation to determine if the plugin
	// would make changes to the resource without actually applying them. This allows for
	// validation and impact assessment before performing actual operations.
	// A positive evaluation (changes that can potentially be applied) triggers calls to the Update, Patch,
	// or Delete verbs.
	// Currently only selected resources have support for this operation type (e.g., pod instances).
	OperatorOperationType_TYPE_EVALUATE OperatorOperationType_Type = 6
)

// Enum value maps for OperatorOperationType_Type.
var (
	OperatorOperationType_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_PATCH",
		2: "TYPE_UPDATE",
		3: "TYPE_CREATE",
		4: "TYPE_DELETE",
		5: "TYPE_DEREGISTER",
		6: "TYPE_EVALUATE",
	}
	OperatorOperationType_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_PATCH":       1,
		"TYPE_UPDATE":      2,
		"TYPE_CREATE":      3,
		"TYPE_DELETE":      4,
		"TYPE_DEREGISTER":  5,
		"TYPE_EVALUATE":    6,
	}
)

func (x OperatorOperationType_Type) Enum() *OperatorOperationType_Type {
	p := new(OperatorOperationType_Type)
	*p = x
	return p
}

func (x OperatorOperationType_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperatorOperationType_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_operator_lifecycle_proto_enumTypes[0].Descriptor()
}

func (OperatorOperationType_Type) Type() protoreflect.EnumType {
	return &file_proto_operator_lifecycle_proto_enumTypes[0]
}

func (x OperatorOperationType_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperatorOperationType_Type.Descriptor instead.
func (OperatorOperationType_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_operator_lifecycle_proto_rawDescGZIP(), []int{3, 0}
}

type OperatorLifecycleResponse_Behavior int32

const (
	// Treated as BEHAVIOR_CONTINUE.
	OperatorLifecycleResponse_BEHAVIOR_UNSPECIFIED OperatorLifecycleResponse_Behavior = 0
	// BEHAVIOR_CONTINUE indicates that this lifecycle hook execution was successful
	// and the operator should proceed with the json_patch (if any).
	// This is the default behavior when behavior is not set.
	OperatorLifecycleResponse_BEHAVIOR_CONTINUE OperatorLifecycleResponse_Behavior = 1
	// BEHAVIOR_REQUEUE indicates that the plugin cannot proceed at this time
	// (e.g., waiting for a dependency to be created) and the operator should
	// requeue the reconciliation without treating it as an error.
	// This allows plugins to handle temporary conditions gracefully.
	OperatorLifecycleResponse_BEHAVIOR_REQUEUE OperatorLifecycleResponse_Behavior = 2
)

// Enum value maps for OperatorLifecycleResponse_Behavior.
var (
	OperatorLifecycleResponse_Behavior_name = map[int32]string{
		0: "BEHAVIOR_UNSPECIFIED",
		1: "BEHAVIOR_CONTINUE",
		2: "BEHAVIOR_REQUEUE",
	}
	OperatorLifecycleResponse_Behavior_value = map[string]int32{
		"BEHAVIOR_UNSPECIFIED": 0,
		"BEHAVIOR_CONTINUE":    1,
		"BEHAVIOR_REQUEUE":     2,
	}
)

func (x OperatorLifecycleResponse_Behavior) Enum() *OperatorLifecycleResponse_Behavior {
	p := new(OperatorLifecycleResponse_Behavior)
	*p = x
	return p
}

func (x OperatorLifecycleResponse_Behavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperatorLifecycleResponse_Behavior) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_operator_lifecycle_proto_enumTypes[1].Descriptor()
}

func (OperatorLifecycleResponse_Behavior) Type() protoreflect.EnumType {
	return &file_proto_operator_lifecycle_proto_enumTypes[1]
}

func (x OperatorLifecycleResponse_Behavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperatorLifecycleResponse_Behavior.Descriptor instead.
func (OperatorLifecycleResponse_Behavior) EnumDescriptor() ([]byte, []int) {
	return file_proto_operator_lifecycle_proto_rawDescGZIP(), []int{5, 0}
}

type OperatorLifecycleCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorLifecycleCapabilitiesRequest) Reset() {
	*x = OperatorLifecycleCapabilitiesRequest{}
	mi := &file_proto_operator_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorLifecycleCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorLifecycleCapabilitiesRequest) ProtoMessage() {}

func (x *OperatorLifecycleCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorLifecycleCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*OperatorLifecycleCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_operator_lifecycle_proto_rawDescGZIP(), []int{0}
}

type OperatorLifecycleCapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This message is OPTIONAL, containing the list of resources
	// for which the lifecycle hook is called
	LifecycleCapabilities []*OperatorLifecycleCapabilities `protobuf:"bytes,1,rep,name=lifecycle_capabilities,json=lifecycleCapabilities,proto3" json:"lifecycle_capabilities,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OperatorLifecycleCapabilitiesResponse) Reset() {
	*x = OperatorLifecycleCapabilitiesResponse{}
	mi := &file_proto_operator_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorLifecycleCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorLifecycleCapabilitiesResponse) ProtoMessage() {}

func (x *OperatorLifecycleCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorLifecycleCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*OperatorLifecycleCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_operator_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *OperatorLifecycleCapabilitiesResponse) GetLifecycleCapabilities() []*OperatorLifecycleCapabilities {
	if x != nil {
		return x.LifecycleCapabilities
	}
	return nil
}

type OperatorLifecycleCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Kubernetes resource group (such as "apps" or empty for core resources)
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// The Kubernetes Kind name (such as "Cluster" or "Pod")
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// The operation type
	OperationTypes []*OperatorOperationType `protobuf:"bytes,3,rep,name=operation_types,json=operationTypes,proto3" json:"operation_types,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OperatorLifecycleCapabilities) Reset() {
	*x = OperatorLifecycleCapabilities{}
	mi := &file_proto_operator_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorLifecycleCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorLifecycleCapabilities) ProtoMessage() {}

func (x *OperatorLifecycleCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorLifecycleCapabilities.ProtoReflect.Descriptor instead.
func (*OperatorLifecycleCapabilities) Descriptor() ([]byte, []int) {
	return file_proto_operator_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *OperatorLifecycleCapabilities) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *OperatorLifecycleCapabilities) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OperatorLifecycleCapabilities) GetOperationTypes() []*OperatorOperationType {
	if x != nil {
		return x.OperationTypes
	}
	return nil
}

type OperatorOperationType struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Type          OperatorOperationType_Type `protobuf:"varint,1,opt,name=type,proto3,enum=cnpgi.operator_lifecycle.v1.OperatorOperationType_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorOperationType) Reset() {
	*x = OperatorOperationType{}
	mi := &file_proto_operator_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorOperationType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorOperationType) ProtoMessage() {}

func (x *OperatorOperationType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorOperationType.ProtoReflect.Descriptor instead.
func (*OperatorOperationType) Descriptor() ([]byte, []int) {
	return file_proto_operator_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *OperatorOperationType) GetType() OperatorOperationType_Type {
	if x != nil {
		return x.Type
	}
	return OperatorOperationType_TYPE_UNSPECIFIED
}

type OperatorLifecycleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED.
	OperationType *OperatorOperationType `protobuf:"bytes,1,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	// This field is REQUIRED
	ClusterDefinition []byte `protobuf:"bytes,2,opt,name=cluster_definition,json=clusterDefinition,proto3" json:"cluster_definition,omitempty"`
	// This field is REQUIRED.
	ObjectDefinition []byte `protobuf:"bytes,3,opt,name=object_definition,json=objectDefinition,proto3" json:"object_definition,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OperatorLifecycleRequest) Reset() {
	*x = OperatorLifecycleRequest{}
	mi := &file_proto_operator_lifecycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorLifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorLifecycleRequest) ProtoMessage() {}

func (x *OperatorLifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_lifecycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorLifecycleRequest.ProtoReflect.Descriptor instead.
func (*OperatorLifecycleRequest) Descriptor() ([]byte, []int) {
	return file_proto_operator_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *OperatorLifecycleRequest) GetOperationType() *OperatorOperationType {
	if x != nil {
		return x.OperationType
	}
	return nil
}

func (x *OperatorLifecycleRequest) GetClusterDefinition() []byte {
	if x != nil {
		return x.ClusterDefinition
	}
	return nil
}

func (x *OperatorLifecycleRequest) GetObjectDefinition() []byte {
	if x != nil {
		return x.ObjectDefinition
	}
	return nil
}

// OperatorLifecycleResponse is used to instruct the CNPG controller on which action
// to take after the plugin execution.
type OperatorLifecycleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is OPTIONAL. Value of this field is a JSONPatch to be applied
	// on the object definition. When behavior is BEHAVIOR_REQUEUE, this field
	// is ignored by the operator.
	JsonPatch []byte `protobuf:"bytes,1,opt,name=json_patch,json=jsonPatch,proto3" json:"json_patch,omitempty"`
	// This field is OPTIONAL. Indicates the behavior that should be used for
	// the current lifecycle hook execution. Defaults to BEHAVIOR_CONTINUE.
	Behavior OperatorLifecycleResponse_Behavior `protobuf:"varint,2,opt,name=behavior,proto3,enum=cnpgi.operator_lifecycle.v1.OperatorLifecycleResponse_Behavior" json:"behavior,omitempty"`
	// This field is OPTIONAL. When behavior is BEHAVIOR_REQUEUE, this specifies
	// the number of seconds to wait before retrying. If not set, zero, or
	// negative, the operator will use its default requeue interval.
	// When behavior is not BEHAVIOR_REQUEUE, this field is ignored.
	// IMPORTANT: the new reconciliation loop may start even before the number
	// of specified seconds.
	RequeueAfter  int64 `protobuf:"varint,3,opt,name=requeue_after,json=requeueAfter,proto3" json:"requeue_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorLifecycleResponse) Reset() {
	*x = OperatorLifecycleResponse{}
	mi := &file_proto_operator_lifecycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorLifecycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorLifecycleResponse) ProtoMessage() {}

func (x *OperatorLifecycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_lifecycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorLifecycleResponse.ProtoReflect.Descriptor instead.
func (*OperatorLifecycleResponse) Descriptor() ([]byte, []int) {
	return file_proto_operator_lifecycle_proto_rawDescGZIP(), []int{5}
}

func (x *OperatorLifecycleResponse) GetJsonPatch() []byte {
	if x != nil {
		return x.JsonPatch
	}
	return nil
}

func (x *OperatorLifecycleResponse) GetBehavior() OperatorLifecycleResponse_Behavior {
	if x != nil {
		return x.Behavior
	}
	return OperatorLifecycleResponse_BEHAVIOR_UNSPECIFIED
}

func (x *OperatorLifecycleResponse) GetRequeueAfter() int64 {
	if x != nil {
		return x.RequeueAfter
	}
	return 0
}

var File_proto_operator_lifecycle_proto protoreflect.FileDescriptor

const file_proto_operator_lifecycle_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/operator_lifecycle.proto\x12\x1bcnpgi.operator_lifecycle.v1\"&\n" +
	"$OperatorLifecycleCapabilitiesRequest\"\x9a\x01\n" +
	"%OperatorLifecycleCapabilitiesResponse\x12q\n" +
	"\x16lifecycle_capabilities\x18\x01 \x03(\v2:.cnpgi.operator_lifecycle.v1.OperatorLifecycleCapabilitiesR\x15lifecycleCapabilities\"\xa6\x01\n" +
	"\x1dOperatorLifecycleCapabilities\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12[\n" +
	"\x0foperation_types\x18\x03 \x03(\v22.cnpgi.operator_lifecycle.v1.OperatorOperationTypeR\x0eoperationTypes\"\xee\x01\n" +
	"\x15OperatorOperationType\x12K\n" +
	"\x04type\x18\x01 \x01(\x0e27.cnpgi.operator_lifecycle.v1.OperatorOperationType.TypeR\x04type\"\x87\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TYPE_PATCH\x10\x01\x12\x0f\n" +
	"\vTYPE_UPDATE\x10\x02\x12\x0f\n" +
	"\vTYPE_CREATE\x10\x03\x12\x0f\n" +
	"\vTYPE_DELETE\x10\x04\x12\x13\n" +
	"\x0fTYPE_DEREGISTER\x10\x05\x12\x11\n" +
	"\rTYPE_EVALUATE\x10\x06\"\xd1\x01\n" +
	"\x18OperatorLifecycleRequest\x12Y\n" +
	"\x0eoperation_type\x18\x01 \x01(\v22.cnpgi.operator_lifecycle.v1.OperatorOperationTypeR\roperationType\x12-\n" +
	"\x12cluster_definition\x18\x02 \x01(\fR\x11clusterDefinition\x12+\n" +
	"\x11object_definition\x18\x03 \x01(\fR\x10objectDefinition\"\xa9\x02\n" +
	"\x19OperatorLifecycleResponse\x12\x1d\n" +
	"\n" +
	"json_patch\x18\x01 \x01(\fR\tjsonPatch\x12[\n" +
	"\bbehavior\x18\x02 \x01(\x0e2?.cnpgi.operator_lifecycle.v1.OperatorLifecycleResponse.BehaviorR\bbehavior\x12#\n" +
	"\rrequeue_after\x18\x03 \x01(\x03R\frequeueAfter\"k\n" +
	"\bBehavior\x12\x18\n" +
	"\x14BEHAVIOR_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11BEHAVIOR_CONTINUE\x10\x01\x12\x14\n" +
	"\x10BEHAVIOR_REQUEUE\x10\x02\"\x04\b\x03\x10\x03*\x12BEHAVIOR_TERMINATE2\xb3\x02\n" +
	"\x11OperatorLifecycle\x12\x9a\x01\n" +
	"\x0fGetCapabilities\x12A.cnpgi.operator_lifecycle.v1.OperatorLifecycleCapabilitiesRequest\x1aB.cnpgi.operator_lifecycle.v1.OperatorLifecycleCapabilitiesResponse\"\x00\x12\x80\x01\n" +
	"\rLifecycleHook\x125.cnpgi.operator_lifecycle.v1.OperatorLifecycleRequest\x1a6.cnpgi.operator_lifecycle.v1.OperatorLifecycleResponse\"\x00B0Z.github.com/cloudnative-pg/cnpg-i/pkg/lifecycleb\x06proto3"

var (
	file_proto_operator_lifecycle_proto_rawDescOnce sync.Once
	file_proto_operator_lifecycle_proto_rawDescData []byte
)

func file_proto_operator_lifecycle_proto_rawDescGZIP() []byte {
	file_proto_operator_lifecycle_proto_rawDescOnce.Do(func() {
		file_proto_operator_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_operator_lifecycle_proto_rawDesc), len(file_proto_operator_lifecycle_proto_rawDesc)))
	})
	return file_proto_operator_lifecycle_proto_rawDescData
}

var file_proto_operator_lifecycle_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_operator_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_operator_lifecycle_proto_goTypes = []any{
	(OperatorOperationType_Type)(0),               // 0: cnpgi.operator_lifecycle.v1.OperatorOperationType.Type
	(OperatorLifecycleResponse_Behavior)(0),       // 1: cnpgi.operator_lifecycle.v1.OperatorLifecycleResponse.Behavior
	(*OperatorLifecycleCapabilitiesRequest)(nil),  // 2: cnpgi.operator_lifecycle.v1.OperatorLifecycleCapabilitiesRequest
	(*OperatorLifecycleCapabilitiesResponse)(nil), // 3: cnpgi.operator_lifecycle.v1.OperatorLifecycleCapabilitiesResponse
	(*OperatorLifecycleCapabilities)(nil),         // 4: cnpgi.operator_lifecycle.v1.OperatorLifecycleCapabilities
	(*OperatorOperationType)(nil),                 // 5: cnpgi.operator_lifecycle.v1.OperatorOperationType
	(*OperatorLifecycleRequest)(nil),              // 6: cnpgi.operator_lifecycle.v1.OperatorLifecycleRequest
	(*OperatorLifecycleResponse)(nil),             // 7: cnpgi.operator_lifecycle.v1.OperatorLifecycleResponse
}
var file_proto_operator_lifecycle_proto_depIdxs = []int32{
	4, // 0: cnpgi.operator_lifecycle.v1.OperatorLifecycleCapabilitiesResponse.lifecycle_capabilities:type_name -> cnpgi.operator_lifecycle.v1.OperatorLifecycleCapabilities
	5, // 1: cnpgi.operator_lifecycle.v1.OperatorLifecycleCapabilities.operation_types:type_name -> cnpgi.operator_lifecycle.v1.OperatorOperationType
	0, // 2: cnpgi.operator_lifecycle.v1.OperatorOperationType.type:type_name -> cnpgi.operator_lifecycle.v1.OperatorOperationType.Type
	5, // 3: cnpgi.operator_lifecycle.v1.OperatorLifecycleRequest.operation_type:type_name -> cnpgi.operator_lifecycle.v1.OperatorOperationType
	1, // 4: cnpgi.operator_lifecycle.v1.OperatorLifecycleResponse.behavior:type_name -> cnpgi.operator_lifecycle.v1.OperatorLifecycleResponse.Behavior
	2, // 5: cnpgi.operator_lifecycle.v1.OperatorLifecycle.GetCapabilities:input_type -> cnpgi.operator_lifecycle.v1.OperatorLifecycleCapabilitiesRequest
	6, // 6: cnpgi.operator_lifecycle.v1.OperatorLifecycle.LifecycleHook:input_type -> cnpgi.operator_lifecycle.v1.OperatorLifecycleRequest
	3, // 7: cnpgi.operator_lifecycle.v1.OperatorLifecycle.GetCapabilities:output_type -> cnpgi.operator_lifecycle.v1.OperatorLifecycleCapabilitiesResponse
	7, // 8: cnpgi.operator_lifecycle.v1.OperatorLifecycle.LifecycleHook:output_type -> cnpgi.operator_lifecycle.v1.OperatorLifecycleResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_operator_lifecycle_proto_init() }
func file_proto_operator_lifecycle_proto_init() {
	if File_proto_operator_lifecycle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_operator_lifecycle_proto_rawDesc), len(file_proto_operator_lifecycle_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_operator_lifecycle_proto_goTypes,
		DependencyIndexes: file_proto_operator_lifecycle_proto_depIdxs,
		EnumInfos:         file_proto_operator_lifecycle_proto_enumTypes,
		MessageInfos:      file_proto_operator_lifecycle_proto_msgTypes,
	}.Build()
	File_proto_operator_lifecycle_proto = out.File
	file_proto_operator_lifecycle_proto_goTypes = nil
	file_proto_operator_lifecycle_proto_depIdxs = nil
}
