// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/postgres.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostgresCapability_RPC_Type int32

const (
	PostgresCapability_RPC_TYPE_UNSPECIFIED PostgresCapability_RPC_Type = 0
	// TYPE_BACKUP indicates that the Plugin is able to
	// enrich the PostgreSQL configuration via the
	// EnrichConfiguration endpoint
	PostgresCapability_RPC_TYPE_ENRICH_CONFIGURATION PostgresCapability_RPC_Type = 1
)

// Enum value maps for PostgresCapability_RPC_Type.
var (
	PostgresCapability_RPC_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_ENRICH_CONFIGURATION",
	}
	PostgresCapability_RPC_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":          0,
		"TYPE_ENRICH_CONFIGURATION": 1,
	}
)

func (x PostgresCapability_RPC_Type) Enum() *PostgresCapability_RPC_Type {
	p := new(PostgresCapability_RPC_Type)
	*p = x
	return p
}

func (x PostgresCapability_RPC_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostgresCapability_RPC_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_postgres_proto_enumTypes[0].Descriptor()
}

func (PostgresCapability_RPC_Type) Type() protoreflect.EnumType {
	return &file_proto_postgres_proto_enumTypes[0]
}

func (x PostgresCapability_RPC_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostgresCapability_RPC_Type.Descriptor instead.
func (PostgresCapability_RPC_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_postgres_proto_rawDescGZIP(), []int{2, 0, 0}
}

type PostgresCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresCapabilitiesRequest) Reset() {
	*x = PostgresCapabilitiesRequest{}
	mi := &file_proto_postgres_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresCapabilitiesRequest) ProtoMessage() {}

func (x *PostgresCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postgres_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*PostgresCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_postgres_proto_rawDescGZIP(), []int{0}
}

type PostgresCapabilitiesResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All the capabilities that the controller service supports. This
	// field is OPTIONAL.
	Capabilities  []*PostgresCapability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresCapabilitiesResult) Reset() {
	*x = PostgresCapabilitiesResult{}
	mi := &file_proto_postgres_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresCapabilitiesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresCapabilitiesResult) ProtoMessage() {}

func (x *PostgresCapabilitiesResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postgres_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresCapabilitiesResult.ProtoReflect.Descriptor instead.
func (*PostgresCapabilitiesResult) Descriptor() ([]byte, []int) {
	return file_proto_postgres_proto_rawDescGZIP(), []int{1}
}

func (x *PostgresCapabilitiesResult) GetCapabilities() []*PostgresCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type PostgresCapability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*PostgresCapability_Rpc
	Type          isPostgresCapability_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresCapability) Reset() {
	*x = PostgresCapability{}
	mi := &file_proto_postgres_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresCapability) ProtoMessage() {}

func (x *PostgresCapability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postgres_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresCapability.ProtoReflect.Descriptor instead.
func (*PostgresCapability) Descriptor() ([]byte, []int) {
	return file_proto_postgres_proto_rawDescGZIP(), []int{2}
}

func (x *PostgresCapability) GetType() isPostgresCapability_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *PostgresCapability) GetRpc() *PostgresCapability_RPC {
	if x != nil {
		if x, ok := x.Type.(*PostgresCapability_Rpc); ok {
			return x.Rpc
		}
	}
	return nil
}

type isPostgresCapability_Type interface {
	isPostgresCapability_Type()
}

type PostgresCapability_Rpc struct {
	Rpc *PostgresCapability_RPC `protobuf:"bytes,1,opt,name=rpc,proto3,oneof"`
}

func (*PostgresCapability_Rpc) isPostgresCapability_Type() {}

type EnrichConfigurationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED and represent the PostgreSQL configuration parameters as
	// generated by the instance manager
	Configs       map[string]string `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichConfigurationRequest) Reset() {
	*x = EnrichConfigurationRequest{}
	mi := &file_proto_postgres_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichConfigurationRequest) ProtoMessage() {}

func (x *EnrichConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postgres_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichConfigurationRequest.ProtoReflect.Descriptor instead.
func (*EnrichConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_postgres_proto_rawDescGZIP(), []int{3}
}

func (x *EnrichConfigurationRequest) GetConfigs() map[string]string {
	if x != nil {
		return x.Configs
	}
	return nil
}

type EnrichConfigurationResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is OPTIONAL. It represent the configuration parameters that need
	// to be changed before applying a new configuration
	Configs       map[string]string `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichConfigurationResult) Reset() {
	*x = EnrichConfigurationResult{}
	mi := &file_proto_postgres_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichConfigurationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichConfigurationResult) ProtoMessage() {}

func (x *EnrichConfigurationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postgres_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichConfigurationResult.ProtoReflect.Descriptor instead.
func (*EnrichConfigurationResult) Descriptor() ([]byte, []int) {
	return file_proto_postgres_proto_rawDescGZIP(), []int{4}
}

func (x *EnrichConfigurationResult) GetConfigs() map[string]string {
	if x != nil {
		return x.Configs
	}
	return nil
}

type PostgresCapability_RPC struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          PostgresCapability_RPC_Type `protobuf:"varint,1,opt,name=type,proto3,enum=cnpgi.identity.v1.PostgresCapability_RPC_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresCapability_RPC) Reset() {
	*x = PostgresCapability_RPC{}
	mi := &file_proto_postgres_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresCapability_RPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresCapability_RPC) ProtoMessage() {}

func (x *PostgresCapability_RPC) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postgres_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresCapability_RPC.ProtoReflect.Descriptor instead.
func (*PostgresCapability_RPC) Descriptor() ([]byte, []int) {
	return file_proto_postgres_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PostgresCapability_RPC) GetType() PostgresCapability_RPC_Type {
	if x != nil {
		return x.Type
	}
	return PostgresCapability_RPC_TYPE_UNSPECIFIED
}

var File_proto_postgres_proto protoreflect.FileDescriptor

const file_proto_postgres_proto_rawDesc = "" +
	"\n" +
	"\x14proto/postgres.proto\x12\x11cnpgi.identity.v1\"\x1d\n" +
	"\x1bPostgresCapabilitiesRequest\"g\n" +
	"\x1aPostgresCapabilitiesResult\x12I\n" +
	"\fcapabilities\x18\x01 \x03(\v2%.cnpgi.identity.v1.PostgresCapabilityR\fcapabilities\"\xe4\x01\n" +
	"\x12PostgresCapability\x12=\n" +
	"\x03rpc\x18\x01 \x01(\v2).cnpgi.identity.v1.PostgresCapability.RPCH\x00R\x03rpc\x1a\x86\x01\n" +
	"\x03RPC\x12B\n" +
	"\x04type\x18\x01 \x01(\x0e2..cnpgi.identity.v1.PostgresCapability.RPC.TypeR\x04type\";\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19TYPE_ENRICH_CONFIGURATION\x10\x01B\x06\n" +
	"\x04type\"\xae\x01\n" +
	"\x1aEnrichConfigurationRequest\x12T\n" +
	"\aconfigs\x18\x01 \x03(\v2:.cnpgi.identity.v1.EnrichConfigurationRequest.ConfigsEntryR\aconfigs\x1a:\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\x19EnrichConfigurationResult\x12S\n" +
	"\aconfigs\x18\x01 \x03(\v29.cnpgi.identity.v1.EnrichConfigurationResult.ConfigsEntryR\aconfigs\x1a:\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xf4\x01\n" +
	"\bPostgres\x12r\n" +
	"\x0fGetCapabilities\x12..cnpgi.identity.v1.PostgresCapabilitiesRequest\x1a-.cnpgi.identity.v1.PostgresCapabilitiesResult\"\x00\x12t\n" +
	"\x13EnrichConfiguration\x12-.cnpgi.identity.v1.EnrichConfigurationRequest\x1a,.cnpgi.identity.v1.EnrichConfigurationResult\"\x00B/Z-github.com/cloudnative-pg/cnpg-i/pkg/postgresb\x06proto3"

var (
	file_proto_postgres_proto_rawDescOnce sync.Once
	file_proto_postgres_proto_rawDescData []byte
)

func file_proto_postgres_proto_rawDescGZIP() []byte {
	file_proto_postgres_proto_rawDescOnce.Do(func() {
		file_proto_postgres_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_postgres_proto_rawDesc), len(file_proto_postgres_proto_rawDesc)))
	})
	return file_proto_postgres_proto_rawDescData
}

var file_proto_postgres_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_postgres_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_postgres_proto_goTypes = []any{
	(PostgresCapability_RPC_Type)(0),    // 0: cnpgi.identity.v1.PostgresCapability.RPC.Type
	(*PostgresCapabilitiesRequest)(nil), // 1: cnpgi.identity.v1.PostgresCapabilitiesRequest
	(*PostgresCapabilitiesResult)(nil),  // 2: cnpgi.identity.v1.PostgresCapabilitiesResult
	(*PostgresCapability)(nil),          // 3: cnpgi.identity.v1.PostgresCapability
	(*EnrichConfigurationRequest)(nil),  // 4: cnpgi.identity.v1.EnrichConfigurationRequest
	(*EnrichConfigurationResult)(nil),   // 5: cnpgi.identity.v1.EnrichConfigurationResult
	(*PostgresCapability_RPC)(nil),      // 6: cnpgi.identity.v1.PostgresCapability.RPC
	nil,                                 // 7: cnpgi.identity.v1.EnrichConfigurationRequest.ConfigsEntry
	nil,                                 // 8: cnpgi.identity.v1.EnrichConfigurationResult.ConfigsEntry
}
var file_proto_postgres_proto_depIdxs = []int32{
	3, // 0: cnpgi.identity.v1.PostgresCapabilitiesResult.capabilities:type_name -> cnpgi.identity.v1.PostgresCapability
	6, // 1: cnpgi.identity.v1.PostgresCapability.rpc:type_name -> cnpgi.identity.v1.PostgresCapability.RPC
	7, // 2: cnpgi.identity.v1.EnrichConfigurationRequest.configs:type_name -> cnpgi.identity.v1.EnrichConfigurationRequest.ConfigsEntry
	8, // 3: cnpgi.identity.v1.EnrichConfigurationResult.configs:type_name -> cnpgi.identity.v1.EnrichConfigurationResult.ConfigsEntry
	0, // 4: cnpgi.identity.v1.PostgresCapability.RPC.type:type_name -> cnpgi.identity.v1.PostgresCapability.RPC.Type
	1, // 5: cnpgi.identity.v1.Postgres.GetCapabilities:input_type -> cnpgi.identity.v1.PostgresCapabilitiesRequest
	4, // 6: cnpgi.identity.v1.Postgres.EnrichConfiguration:input_type -> cnpgi.identity.v1.EnrichConfigurationRequest
	2, // 7: cnpgi.identity.v1.Postgres.GetCapabilities:output_type -> cnpgi.identity.v1.PostgresCapabilitiesResult
	5, // 8: cnpgi.identity.v1.Postgres.EnrichConfiguration:output_type -> cnpgi.identity.v1.EnrichConfigurationResult
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_postgres_proto_init() }
func file_proto_postgres_proto_init() {
	if File_proto_postgres_proto != nil {
		return
	}
	file_proto_postgres_proto_msgTypes[2].OneofWrappers = []any{
		(*PostgresCapability_Rpc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_postgres_proto_rawDesc), len(file_proto_postgres_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_postgres_proto_goTypes,
		DependencyIndexes: file_proto_postgres_proto_depIdxs,
		EnumInfos:         file_proto_postgres_proto_enumTypes,
		MessageInfos:      file_proto_postgres_proto_msgTypes,
	}.Build()
	File_proto_postgres_proto = out.File
	file_proto_postgres_proto_goTypes = nil
	file_proto_postgres_proto_depIdxs = nil
}
